### ISSUE TITLE
How to add data to data/zoning folder?

### ISSUE THREAD

**Issue by sid-kap** [zoningspace/zoning.space#19]
Would I need permissions in the S3 directory to contribute shapefiles?

**Comment by sid-kap** [comment]
Also, have you considered using git lfs rather than s3? (That would make it easier for contributors to add data without needing s3 permissions.)

**Comment by sid-kap** [comment]
bump.... @hunterowens @mattwigway

**Comment by mattwigway** [comment]
@sid-kap I believe we've resolved this over email to get you access to the data; feel free to re-open or email again if that's not the case.

**Comment by sid-kap** [comment]
What about the second question: have you considered using git lfs?

**Comment by mattwigway** [comment]
Yeah, we decided against it due to cost; the project hosting costs are
currently being paid by Hunter and I.
