### ISSUE TITLE
San Francisco parking requirements don't look right

### ISSUE THREAD

**Issue by sid-kap** [zoningspace/zoning.space#20]
I was under the impression that most SF neighborhoods had removed their parking requirements, as described in [this article](https://www.livablecity.org/parking-history-sf/).
Are the neighborhood plan parking exemptions missing here?

**Comment by mattwigway** [comment]
Hmm, I'm not sure. I used the parking requirements described in the municipal code, so I would expect that to incorporate neighborhood plan exemptions (there are, for example, a bunch of neighborhood commercial districts with different parking requirements). Do you have a specific neighborhood that appears incorrect?

**Comment by sid-kap** [comment]
Yeah, looks like most of those parking reductions were only for the commercial strips, not the actual neighborhoods, and don't apply to RH-1 and RH-2 zoning. So it's a lot less than I had thought. So the zoning.space map is probably correct
