### ISSUE TITLE
Fix spurious light rail areas in Sacramento

### ISSUE THREAD

**Issue by mattwigway** [zoningspace/zoning.space#26]
Due to a spatial overlay issue in Sacramento, all areas around light-rail stations were showing that high-density was permitted around light rail stations, when it should have only been in industrial areas and the R Street Corridor. What happened was that the polygons around the light rail stations accidentally leaked into the output (although they wouldn't have had many attributes).

![image](https://user-images.githubusercontent.com/566958/38909066-d83b9706-4277-11e8-9b98-4b3e72616251.png)

**Comment by sid-kap** [comment]
LOL, does the Policy Club 827 project live on?

**Comment by mattwigway** [comment]
Yup. Zoning. Space was created for 827, but was designed to support all
types of research (including, in all likelihood, my dissertation).

On Apr 17, 2018 8:38 PM, "Sid Kapur" <notifications@github.com> wrote:

LOL, does the Policy Club 827 project live on?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/zoningspace/zoning.space/issues/26#issuecomment-382246289>,
or mute the thread
